[tool.ruff]
line-length = 88
extend-exclude = ["alembic"]

# Enable Pyflakes `E` and `F` codes by default.
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

# [tool.ruff.format]
# skip-magic-trailing-comma = false

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.mypy]
python_version = "3.11"
mypy_path = "src"
strict = true
warn_unreachable = true
implicit_reexport = true
show_error_codes = true
show_column_numbers = true
ignore_missing_imports = true
warn_unused_ignores = false
plugins = "sqlalchemy.ext.mypy.plugin"
exclude = "alembic"

[[tool.mypy.overrides]]
module = [
    "pathspec.*",
    "IPython.*",
    "colorama.*",
    "tokenize_rt.*",
    "uvloop.*",
    "_black_version.*",
]
ignore_missing_imports = true

# CI only checks src/, but in case users are running LSP or similar we explicitly ignore
# errors in test data files.
[[tool.mypy.overrides]]
module = ["tests.data.*"]
ignore_errors = true
