services:
    app:
        image: app_image
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: app
        depends_on:
            - app_db
        volumes:
            - ..:/application
        ports:
            - "8000:8000"
        env_file:
            - ../.env

    app_db:
        image: library/postgres:14.1
        container_name: app_db
        hostname: app_db
        volumes:
            - app_pg_data:/var/lib/postgresql/data
            - app_pg_data_backups:/backups
            - ../scripts/postgres:/scripts
        ports:
            - "65432:5432"
        env_file:
            - ../.env

    app_redis:
        image: redis:6.2-alpine
        hostname: redis
        container_name: app_redis
        command:
            - 'redis-server'
            - '--requirepass myStrongPassword'
        ports:
            - 36379:6379

volumes:
    app_pg_data:
        driver: "local"
    app_pg_data_backups:
        driver: "local"

networks:
    default:
        name: core_application_network
